name: Build and Attach Installer

on:
#  release:
#    types: [created]
#    branches:
#      - main
    push:
      branches:
        - workflow
jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Specify your .NET version here

    - name: Restore dependencies
      run: dotnet restore video-takeoff-control/video-takeoff-control.sln

    - name: Build solution
      run: msbuild video-takeoff-control\video-takeoff-control\video-takeoff-control.csproj /p:Configuration=Release /m:1 #dotnet build video-takeoff-control/video-takeoff-control/video-takeoff-control.csproj --configuration Release

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Build Installer Project
      run: |
        devenv video-takeoff-control/video-takeoff-control-setup/video-takeoff-control-setup.vdproj /Rebuild Release

    - name: Create release asset
      run: |
        cd ./video-takeoff-control-setup/Release
        zip -r ../installer.zip ./
      working-directory: video-takeoff-control

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./video-takeoff-control/installer.zip
        asset_name: installer.zip
        asset_content_type: application/zip
