name: Build and Attach Installer

on:
#  release:
#    types: [created]
#    branches:
#      - main
    
    push:
      branches:
        - main
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Specify your .NET version here

    - name: Restore dependencies
      run: dotnet restore
      working-directory: /video-takeoff-control

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Publish Installer Project
      run: dotnet publish video-takeoff-control-setup/video-takeoff-control-setup.vdproj --configuration Release --output ./output

    - name: Create release asset
      run: |
        cd ./output
        zip -r ../installer.zip ./

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./installer.zip
        asset_name: installer.zip
        asset_content_type: application/zip
